[platformio]
disable_auto_sync = true
telemetry = disabled

[env:esp32-s3-tft7735-v100]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyACM0
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
    -DFW_VERSION=\"1.0.0\"
partition_table = partitions_ota.csv
monitor_filters = esp32_exception_decoder
