[platformio]
src_dir = src

[env:esp8266oled]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D CORE_DEBUG_LEVEL=1
  -D PROJECT_NAME="esp8266oled"
  -D FW_VERSION=\"20261006-v1.0\"
  -D PROJECT_ID=\"default\"
  -D WEB_PORT=8822
lib_deps =
  olikraus/U8g2@^2.35.4
  ESP8266WebServer@^2.0.4
